version: '3.3'
services:
  dev_minio:
    image: quay.io/minio/minio:latest
    environment:
      - 'MINIO_ROOT_USER=root'
      - 'MINIO_ROOT_PASSWORD=BcHNLq@9sM'
      - 'MINIO_CONSOLE_ADDRESS=:9001'
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/data'
    command: server /data --console-address ":9001"
    restart: always
    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live' ]
      interval: 30s
      timeout: 20s
      retries: 3

  dev_postgres:
    image: postgres:17.5-alpine
    environment:
      - 'POSTGRES_DB=main'
      - 'POSTGRES_USER=root'
      - 'POSTGRES_PASSWORD=BcHNLq@9sM'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
    driver: local
  minio_data:
    driver: local
