version: '3.3'
services:
  minio-mock:
    image: quay.io/minio/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - "~/minio/data:/data"
    environment:
      - MINIO_ROOT_USER: root
      - MINIO_ROOT_PASSWORD: root
